baseURL: 'http://wwww.jiangzeyi.com'
languageCode: 'zh-CN'
title: 泽毅
theme: easy-theme

taxonomies:
  tag: tags
  series: series

params:
  homeInfo:
    title: 笔随心动
    subtitle: 记录心中所得，心中所思，心中所想
  menu:
    - name: Home
      url: /
      weight: 10
    - name: Tags
      url : /tags
      weight: 10
    - name: RSS
      url : /index.xml
      weight: 10
    - name: About
      url : /about
      weight: 10
  subtitle: subtitle
