baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme='simple-theme'
copyright = '© 2023 ABC Widgets, Inc.'

[[menus.main]]
name = '首页'
pageRef = '/'
weight = 10

[[menus.main]]
name = '文章'
pageRef = '/posts'
weight = 20

[services]
  [services.googleAnalytics]
    id = 'G-9WKZWYQK3N'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
